// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AttributeCSVParser
{
	public static Attributes ParseCSV(String csv) {

		Attributes d = new Attributes();

		// TODO FIXME: This is NOT going to be a robust implementation of CSV parsing.
		int i =0;
		foreach (String line in csv.Split ('\n')) {
			//skip header
			i++;
			if (i == 1) { continue; }
			String[] fields = line.Split (',');
			try {
				d.Add(fields[0], float.Parse(fields[1]));
			} catch(System.FormatException e) {
				Debug.Log ("uh oh, parse error in data file.");
				Debug.Log (line);
				Debug.Log(fields);
				Debug.Log (e.Message);
			}


		}
		d.Name = "";
		return d;
	}

	public static Attributes ParseCSV(String csv, String name) {
		Attributes d = ParseCSV (csv);
		d.Name = name;
		return d;
	}
}

