// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
public class Attributes
{

	private Dictionary <string, float> data;
	private float max = 0;
	private string name = "";

	public Attributes ()
	{
		data = new Dictionary<string, float>();
	}

	public void Add(string id, float value) {
		data.Add(id, value);
		if (value > max) {
			max = value;
		}
	}

	public float Get(string id) 
	{
		if (data.ContainsKey(id) ) {
			return data[id];
		} else {
			Debug.Log("WARNING: no attribute value for " + id);
			return 0;
		}
	}

	/*   retval  	ceil
		 ----  =    ------
         value    	max
	*/


	public string Name {
		get {
			return this.name;
		}
		set {
			this.name = value;
		}
	}

	public float Max {
		get {
			return this.max;
		}
	}
}

